name: 'Vuldet'
description: 'Greet someone'

outputs:
  found-vuls:
    description: "list of files and snippets with detected vulnerability"
    value: ${{ env.found-secrets }}

env:
  IP_ADDR: '158.160.32.83'
  found-secrets: ''
  

runs:
  using: "composite"
  
  steps:
    - run: echo Hello ${{ inputs.who-to-greet }}.
      shell: bash
      
    - name: Get changed files
      id: changed-files
      uses: tj-actions/changed-files@v34
      with:
        files_ignore_separator: " "
      
    - name: Write File
      run: cd ${{ github.action_path }} && echo ${{ steps.changed-files.outputs.all_changed_files }} > ${{ github.action_path }}/pathes.txt && cat pathes.txt
      shell: bash
  
    # получение ip-адреса
 #   - id: ip_address_server
 #     run: |
 #       cd ${{ github.action_path }} && wget -o wget.txt detsec.ddns.net
 #       cd ${{ github.action_path }} && cat wget.txt
 #       cd ${{ github.action_path }} && echo "IP_ADDR=$(grep "Location" wget.txt | awk -F/ '{print $3}' | awk -F: '{print $1}')" >> $GITHUB_ENV
 #     shell: bash

    # send request
    - id: send_request
      run: |
         curl -F "file=@${{ steps.changed-files.outputs.all_changed_files }}" http://$IP_ADDR:8000/uploadfile >> ${{ github.action_path }}/otchet.txt
      shell: bash
      
      
    - id: list-
    -secrets
      run: |
         cat ${{ github.action_path }}/otchet.txt
         echo "found-secrets<<EOF" >> $GITHUB_ENV
         echo -e $(cat ${{ github.action_path }}/otchet.txt) >> $GITHUB_ENV
         echo 'EOF' >> $GITHUB_ENV
      shell: bash
      
      
#    - name: show-variable-output
 #     run: echo -e ${{ steps.list-found-secrets.outputs.found-secrets }}
#      run: echo -e ${{ env.found-secrets }}
#      shell: bash
      
    - name: if there any secrets
      run:  if grep -v 'Пароли не найдены' ${{ github.action_path }}/otchet.txt; then exit 1; fi
      shell: bash     



# $mail->SMTPSecure='ssl';
# $mail->Host=""smtp.gmail.com"";
# //$mail->Host=""smtp.hostinger.in"";
# $mail->isHTML();
# $mail->Password='123';
# $mail->Username=<EMAIL>;
# $mail->SetFrom(<EMAIL>);
# $mail->AddReplyTo($email);
# $mail->FromName=$first_name."" "".$last_name;
# $mail->Subject=""New Message from digiOmega Contact Form"";
# $email_content = ""Name: $first_name + $last_name <br>"";
# $email_content .= ""Phone: $phone <br>"";",1,php
