name: Lint Code Base
on: push
jobs:
  linter:
    runs-on: ubuntu-latest
    steps:
      # Переключение на текущую ветку
      - uses: actions/checkout@v2
      # Вызов Super Linter
      - uses: docker://github/super-linter:v2.1.0
