name: Python application

on:
  push:
jobs:
  build:
    runs-on: ubuntu-latest 
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.11
      uses: actions/setup-python@v4
      with:
        python-version: "3.11"
    - name: Test with pytest
    - uses: fylein/python-pytest-github-action@v2
